### PR TITLE
Opt buffer reads

### PR DESCRIPTION
**Pull request by aletomsic**
This pull-request includes both for batch updates (Manuel) and reads (Alejandro).

### CODE REVIEW

**Comment by bieniusa** [comment]
The riak-test inter_dc_repl_test is failing.

inter_dc_repl_test failed: {{badmatch,{badrpc,{'EXIT',{noproc,{gen_server,call,[inter_dc_manager,{start_receiver,8091},infinity]}}}}},[{inter_dc_repl_test,confirm,0,[{file,"riak_test/inter_dc_repl_test.erl"},{line,15}]}]}

Please fix!
Can you please make sure that in the modules at least the exported functions have type annotations?

**Comment by aletomsic** [comment]
Deepthi or Manuel, could you check this?
Does this not happen in opt-buffer-writes?


Alejandro Tomsic

**Comment by bieniusa** [comment]
Ale: What has happened to this branch?

Is it meanwhile obsolete?

**Comment by tcrain** [comment]
These optimisations are not included in https://github.com/SyncFree/antidote/pull/139
Once https://github.com/SyncFree/antidote/pull/139 is merged to master, we should add these in?

**Comment by aletomsic** [comment]
I think this branch must have been left obsolete if it was not included in what tyler used to apply his changes. 
It addressed the case when a coordinator has to send, in a static transaction, multiple reads to a single partitions. It just packed them in a single message instead of sending a message per read. 
Tyler, you're sure this was left out?

**Comment by tcrain** [comment]
Yes, I angbrav 's changes are in https://github.com/SyncFree/antidote/pull/139 but not your changes for the batching that you added

**Comment by bieniusa** [comment]
Can this one be closed?

**Comment by tcrain** [comment]
Certain changes in this branch (performing batch reads and batch updates) do not currently exist in master.  They should give a big performance boot in static transactions so it might be worthwhile for someone to merge this with the current version of master so these changes are not lost.

**Comment by aletomsic** [comment]
I’ll take a look at how easy it would be to merge it now with master.

**Comment by aletomsic** [comment]
Please give some more time. I'll take care of it.

**Comment by bieniusa** [comment]
@aletomsic  Please re-open when you finished.

**Pull request closed without merging**
