### PR TITLE
Txs single partition

### PR DESCRIPTION
**Pull request by angbrav**
Optimisation for transactions that affect only one partition. I have also added two tests to check that works. The operations clocksi_iprepare and clocks_icommit used for testing corner cases in the algorithm are still in the API. For benchmarking, the new operation clocks_full_icommit(we can change the name) should be used since it will take advantage of the optimisation and likely improve results.

### CODE REVIEW

**Comment by bieniusa** [comment]
Manuel, this seems to be an optimization we still want to have, right?
Can you prepare it for merging into master?

**Comment by tcrain** [comment]
These changes are included in https://github.com/SyncFree/antidote/pull/139

**Comment by bieniusa** [comment]
Can this one be closed?

**Comment by angbrav** [comment]
The changes are included in Tylers changes, which were already merged in master. I would say we can close it.

Manuel

**Pull request closed without merging**
