### PR TITLE
Fix join local cluster scripts

### PR DESCRIPTION
**Pull request by ergl**

### CODE REVIEW

**Comment by bieniusa** [comment]
@cmeiklejohn What about the mess support for Antidote? If this is not option anymore, we should clean up the scripts.

**Comment by cmeiklejohn** [comment]
What is `mess`?

**Comment by bieniusa** [comment]
@ergl What is the state of this pull request?
@cmeiklejohn What about the Mesos support for Antidote? If this is not option anymore, we should clean up the scripts.

**Comment by ergl** [comment]
@bieniusa I haven't really touched this branch in a while, but apart from the changes to `bin/env`, I don't think this PR is needed anymore. I might be wrong on this, but it seems like using docker for local multi-node deployments is better than the current scripts in this branch.

**Pull request closed without merging**
