### PR TITLE
[WIP] Deployment Branch

### PR DESCRIPTION
**Pull request by cmeiklejohn**
- [x] Docker image for deployment.
- [ ] Script to launch multiple clusters.

### CODE REVIEW

**Comment by mweberUKL** [comment]
Seems like you start the console for starting Antidote. This means that you can only start in interactive mode.

Can you maybe reuse some parts of the script I wrote for starting an Antidote-node standalone in docker? This should also resolve the problem of connecting to the node using RPC (if needed) because it fixes the RPC port to be 9100.

See my repo: https://github.com/mweberUKL/docker-antidote

**Comment by cmeiklejohn** [comment]
We're going to use the code we have for Lasp that automates all of this for Amazon.

**Comment by peterzeller** [comment]
Maybe we should also add Matias' Dockerfile to the repo or to the documentation. For end-users it seems to be better, since it is smaller, sets up the ports correctly, can be started in noninteractive mode, and has some variables to configure the node names etc.

**Comment by cmeiklejohn** [comment]
Yes, I suggest that his Dockerfile is added into the `Dockerfiles` directory with the name `antidote-local` so it's clear that it can be used to run a local node.

**Comment by cmeiklejohn** [comment]
Abandoning.

**Pull request closed without merging**
