### PR TITLE
Fix edoc

### PR DESCRIPTION
**Pull request by bieniusa**

### CODE REVIEW

**Comment by bieniusa** [comment]
@preguica Can you check that running `./rebar3 edoc` works for you?
It should generate the docs in folder `edoc`.

**Comment by preguica** [comment]
I am getting this:

Air-de-Nuno-2:antidote nmp$ ./rebar3 edoc
===> Verifying dependencies...
===> Plugin protobuffs does not export init/1. It will not be used.
===> Plugin protobuffs does not export init/1. It will not be used.
===> Compiling antidote
===> Running edoc for antidote
/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/antidote.erl,
function clocksi_istart_tx/2: at line 385: @spec arity does not match.
edoc: skipping source file
'/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/antidote.erl':
{'EXIT',

                           error}.
edoc: skipping source file
'/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/binary_utilities.erl':
{'EXIT',

                                   {{badmatch,

                                     {atom,

                                      31,

                                      '?VERSION_BITS'}},

                                    [{edoc_specs,

                                      d2e,

                                      2,

                                      [{file,

                                        "edoc_specs.erl"},

                                       {line,

                                        364}]},

                                     {edoc_specs,

                                      '-d2e/2-lc$^0/1-0-',

                                      2,

                                      [{file,

                                        "edoc_specs.erl"},

                                       {line,

                                        418}]},

                                     {edoc_specs,

                                      '-d2e/2-lc$^0/1-0-',

                                      2,

                                      [{file,

                                        [...]},

                                       {line,...}]},

                                     {edoc_specs,

                                      d2e,

                                      2,

                                      [{file,...},

                                       {...}]},

                                     {edoc_specs,

                                      spec,

                                      2,

                                      [{...}|...]},

                                     {edoc_extract,

                                      selected_specs,

                                      2,

                                      [...]},

                                     {edoc_extract,

                                      get_tags,

                                      6,...},

                                     {edoc_extract,

                                      get_tags,...}]}}.
/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/logging_vnode.erl:
at line 738: syntax error before: '{'
edoc: skipping source file
'/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/logging_vnode.erl':
{'EXIT',

                                error}.
/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/materializer_vnode.erl:
at line 261: syntax error before: '{'
edoc: skipping source file
'/Users/nmp/Work/WORK/current/Antidote/antidote/apps/antidote/src/materializer_vnode.erl':
{'EXIT',

                                     error}.
edoc: error in doclet 'edoc_doclet': {'EXIT',error}.
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or
consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3
report "your command"`
Air-de-Nuno-2:antidote nmp$

**Comment by bieniusa** [comment]
Are you sure that you are running it on the right branch?

Some of the issues look like the ones that I have fixed.
Quickcheck: Does the rebar.configure file have an edoc section?

**Comment by bieniusa** [comment]
#316 Fixed

**Pull request merged**
