### PR TITLE
Parallel reads

### PR DESCRIPTION
**Pull request by aletomsic**
This PR addesses partially issue #248.
It adds parallel reads for the interactive_txn when reading multiple objects using the 
interactive read_objects call.

### CODE REVIEW

**Comment by aletomsic** [comment]
Note that it contains the changes in PRs #252 and #250.
Please merge after those.

**Comment by bieniusa** [comment]
@aletomsic Can you resolve the conflicts?

**Comment by aletomsic** [comment]
done.

**Comment by aletomsic** [comment]
wait. there are some issues. I'll let you know when they're fixed.

**Comment by aletomsic** [comment]
now it's fine to merge.

**Comment by bieniusa** [comment]
I am not entirely convinced that the fix with the pid() in the type is correct. But we need to get the changes in...

**Pull request merged**
