### PR TITLE
made make rel run eunit tests

### PR DESCRIPTION
**Pull request by aletomsic**
this solves issue #239 .

This should be merged after PR #238, otherwise the build will fail.

### CODE REVIEW

**Comment by aletomsic** [comment]
This should be safe to merge now.

**Comment by bieniusa** [comment]
The travis builds both fail. Please fix.

**Comment by aletomsic** [comment]
"This should be merged after PR #238, otherwise the build will fail."

Now that you merged it, should be safe.

**Comment by aletomsic** [comment]
For some reason, this still fails on erlang 19 and not on 18.3.
Strange, I run on erlang19 and does not fail locally.
Will take a closer look.

**Comment by aletomsic** [comment]
This happened in the first travis build:

https://travis-ci.org/SyncFree/antidote/jobs/168910708#L2183-L2197

After that, it builds fine. 
Deepthi and I tried building locally and works. 

What could be happening?

**Comment by mweberUKL** [comment]
From the error it looks like eunit tries to write the logs of executing the tests to the `logs` folder, which at that point in time does not exist. Please note that eunit will not create the folder by itself. In the tools.mk file, the target for running eunit takes care of creating the folder. The other make targets will not do that.

> On 19 Oct 2016, at 16:01, Alejandro Zlatko Tomsic <notifications@github.com> wrote:
> 
> This happened in the first travis build:
> 
> https://travis-ci.org/SyncFree/antidote/jobs/168910708#L2183-L2197
> 
> After that, it builds fine. 
> Deepthi and I tried building locally and works.
> 
> What could be happening?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----
Mathias Weber, M.Sc.
AG Softwaretechnik
TU Kaiserslautern
E-Mail: m_weber@cs.uni-kl.de
Raum: 34-406
https://softech.cs.uni-kl.de/homepage/de/staff/MathiasWeber

**Comment by cmeiklejohn** [comment]
I'm confused, why is building a release running the eunit tests?

**Comment by bieniusa** [comment]
Yeah, Chris is right.

We should better add the tests and dialyzer to the „make compile“ target.

The problem that Travis shows is unrelated to the eunit tests, I think.

12:56:45.019 [error] Error in process <0.1148.0> on node 'ct@testing-gce-68fb3995-a1c7-4e76-a01f-4ccb5646b738' with exit value:
{{badmatch,{error,{antidote,{bad_return,{{antidote_app,start,[normal,[]]},{'EXIT',{{badmatch,{badrpc,{'EXIT',{noproc,{gen_server,call,[inter_dc_query,{del_dc,{'dev3@testing-gce-68fb3995-a1c7-4e76-a01f-4ccb5646b738',{1476,881694,905577}}},infinity]}}}}},[{inter_dc_manager,'-forget_dc/1-fun-2-',2,[{file,"/home/travis/build/SyncFree/antidote/_build/default/lib/antidote/src/inter_dc_manager.erl"},{line,233}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{inter_dc_manager,forget_dc,1,[{file,"/home/travis/build/SyncFree/antidote/_build/default/lib/antidote/src/inter_dc_manager.erl"},{line,233}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{inter_dc_manager,reconnect_dcs_after_restart,1,[{file,"/home/travis/build/SyncFree/antidote/_build/default/lib/antidote/src/inter_dc_manager.erl"},{line,197}]},{inter_dc_manager,check_node_restart,0,[{file,"/home/travis/build/SyncFree/antidote/_build/default/lib/antidote/src/inter_dc_manager.erl"},{line,187}]},{antidote_app,start,2,[{file,"/home/travis/build/SyncFree/antidote/_build/default/lib/antidote/src/antidote_app.erl"},{line,60}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}}},[{test_utils,start_node,2,[{file,"test_utils.erl"},{line,211}]},{test_utils,'-pmap/2-fun-0-',4,[{file,"test_utils.erl"},{line,68}]}]}


	Annette

**Comment by bieniusa** [comment]
This change is obsolete following our discussions.

**Pull request closed without merging**
